# Generated by Django 2.0.5 on 2019-03-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='address_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='address_line1_check',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='address_zip',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='address_zip_check',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='exp_month',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='exp_year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='livemode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='token_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
