# Generated by Django 2.1.7 on 2019-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0003_auto_20190328_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='livemode',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
