
version: '3.5'

services:

  headshot_backend:
    container_name: headshot-backend
    build: 
      context: .
      dockerfile: Dockerfile
    # command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - '.:/usr/src/backend'
    ports:
      - "8000:8000"
    environment:
      - DATABASE_ENGINE='django.db.backends.postgresql_psycopg2'
      - DATABASE_NAME=headshot
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=192.168.0.121
      - DATABASE_PORT=5432
