# Generated by Django 2.0.5 on 2019-03-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
