# Generated by Django 2.0.5 on 2019-05-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantity', '0002_auto_20190317_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_quantities', to='production.Production'),
        ),
    ]
