# Generated by Django 2.0.5 on 2019-03-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quantity', '0002_auto_20190317_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('cloudinary_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Reviewing', 'Reviewing'), ('In Progress', 'In Progress'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Requested', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_headshots', to='quantity.Quantity')),
            ],
            options={
                'db_table': 'headshot',
                'ordering': ('id', 'updated_at', 'email', 'file_name'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='headshot',
            unique_together={('id',)},
        ),
    ]
