# Generated by Django 2.0.5 on 2019-03-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headshot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshot',
            name='cloudinary_image_secure_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='headshot',
            name='height',
            field=models.IntegerField(blank=True, default=500),
        ),
        migrations.AddField(
            model_name='headshot',
            name='image_format',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='headshot',
            name='public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='headshot',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='headshot',
            name='width',
            field=models.IntegerField(blank=True, default=400),
        ),
    ]
