# Generated by Django 2.0.5 on 2019-03-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headshot', '0003_auto_20190327_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshot',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
