# Generated by Django 2.0.5 on 2019-05-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headshot', '0004_auto_20190327_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshot',
            name='doc_secure_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='headshot',
            name='doc_url',
            field=models.URLField(blank=True),
        ),
    ]
