# Generated by Django 2.0.5 on 2019-05-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headshot', '0005_auto_20190506_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshot',
            name='doc_format',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='headshot',
            name='doc_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='headshot',
            name='doc_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='headshot',
            name='doc_size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
