# Generated by Django 2.1.7 on 2019-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headshot', '0007_auto_20190506_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshot',
            name='doc_preview_secure_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='headshot',
            name='doc_preview_url',
            field=models.URLField(blank=True),
        ),
    ]
