# Generated by Django 2.1.7 on 2019-05-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headshot', '0008_auto_20190513_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshot',
            name='doc_format',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
